# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 5bbfe58ecdfa39618a9b2ef0368d5aef7fa93a0724872e085ae5d4c79c7e6d29b4438b109c191304ea636ed4a792fbd06a2e30a66d6326f6d23e7ff724092870

test:
  domain_name: example.com 
  secret_key_base: 65568344244b53cf3668e56aca65073e5a6028a2fbf2282809e68115544b5672871b34179e7ee6d12b2181113606df994ae8c212983096a303bbe69915a16b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
